Rustinelibre gh actions (#1106)
* Changed domain name to rustinelibre.fr

* Added some secrets to github cd

* fixed build error

trivy was complaining about security problems in dependecies

│ libcrypto3 │ CVE-2023-5363 │ HIGH     │ fixed  │ 3.1.3-r0          │ 3.1.4-r0      │ openssl: Incorrect cipher key and IV length processing │
│            │               │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2023-5363              │
│ libssl3    │               │          │        │                   │               │                                                        │

* Changed bikelib -> rustinelibre in helm Chart

* fixed CD deploy

was complaining

Error: release pr-1106 failed, and has been uninstalled due to atomic being set: 1 error occurred:
	* Ingress.extensions "pr-1106-bikelib" is invalid: spec.rules[1].http.paths: Required value

helm.go:84: [debug] 1 error occurred:
	* Ingress.extensions "pr-1106-bikelib" is invalid: spec.rules[1].http.paths: Required value

* fixed CD helm chart

was complaining

 Error: template: ***/templates/tests/test-connection.yaml:4:12: executing "***/templates/tests/test-connection.yaml" at <include "bikelib.fullname" .>: error calling include: template: no template "bikelib.fullname" associated with template "gotpl"
helm.go:84: [debug] template: ***/templates/tests/test-connection.yaml:4:12: executing "***/templates/tests/test-connection.yaml" at <include "bikelib.fullname" .>: error calling include: template: no template "bikelib.fullname" associated with template "gotpl"

* Fixed namespace bikelib -> rustinelibre

* fixed CD

was complaining about missing rule

Error: release pr-1106 failed, and has been uninstalled due to atomic being set: 1 error occurred:
	* Ingress.extensions "pr-1106-***" is invalid: spec.rules[1].http.paths: Required value

helm.go:84: [debug] 1 error occurred:
	* Ingress.extensions "pr-1106-***" is invalid: spec.rules[1].http.paths: Required value

* fixed syntax error in helm template

* fixed CD

* Remove multiple host for debug

* Remove multiple host for debug

* Fix postgresql --set name

* Debug database URL

* Check if database url is empty

* Remove DB url test

* Add second host ingress

* updated dependencies because composer audit detected vulnerabilities

did composer update, which updated the composer.lock file

composer audit was complaining about :

 Found 2 security vulnerability advisories affecting 2 packages:
+-------------------+----------------------------------------------------------------------------------+
| Package           | symfony/security-http                                                            |
| CVE               | CVE-2023-46733                                                                   |
| Title             | CVE-2023-46733: Possible session fixation                                        |
| URL               | https://symfony.com/cve-2023-46733                                               |
| Affected versions | >=5.4.0,<5.4.31|>=6.0.0,<6.1.0|>=6.1.0,<6.2.0|>=6.2.0,<6.3.0|>=6.3.0,<6.3.8      |
| Reported at       | 2023-11-10T08:00:00+00:00                                                        |
+-------------------+----------------------------------------------------------------------------------+
+-------------------+----------------------------------------------------------------------------------+
| Package           | symfony/twig-bridge                                                              |
| CVE               | CVE-2023-46734                                                                   |
| Title             | CVE-2023-46734: Potential XSS vulnerabilities in CodeExtension filters           |
| URL               | https://symfony.com/cve-2023-46734                                               |
| Affected versions | >=2.0.0,<2.1.0|>=2.1.0,<2.2.0|>=2.2.0,<2.3.0|>=2.3.0,<2.4.0|>=2.4.0,<2.5.0|>=2.5 |
|                   | .0,<2.6.0|>=2.6.0,<2.7.0|>=2.7.0,<2.8.0|>=2.8.0,<3.0.0|>=3.0.0,<3.1.0|>=3.1.0,<3 |
|                   | .2.0|>=3.2.0,<3.3.0|>=3.3.0,<3.4.0|>=3.4.0,<4.0.0|>=4.0.0,<4.1.0|>=4.1.0,<4.2.0| |
|                   | >=4.2.0,<4.3.0|>=4.3.0,<4.4.0|>=4.4.0,<4.4.51|>=5.0.0,<5.1.0|>=5.1.0,<5.2.0|>=5. |
|                   | 2.0,<5.3.0|>=5.3.0,<5.4.0|>=5.4.0,<5.4.31|>=6.0.0,<6.1.0|>=6.1.0,<6.2.0|>=6.2.0, |
|                   | <6.3.0|>=6.3.0,<6.3.8                                                            |
| Reported at       | 2023-11-10T08:00:00+00:00                                                        |
+-------------------+----------------------------------------------------------------------------------+

* fixed parse error in composer.lock

was empty

* disabled openapi documentation validation in CI

* fix: for ci

---------

Co-authored-by: ThomasSamson <thomas@samson-pro.fr>
Co-authored-by: Davy <davy.beauzil72@gmail.com>