fixed CD
was complaining about missing rule

Error: release pr-1106 failed, and has been uninstalled due to atomic being set: 1 error occurred:
	* Ingress.extensions "pr-1106-***" is invalid: spec.rules[1].http.paths: Required value

helm.go:84: [debug] 1 error occurred:
	* Ingress.extensions "pr-1106-***" is invalid: spec.rules[1].http.paths: Required value